# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jakewendt-ruby_extension}
  s.version = "1.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jake"]
  s.date = %q{2011-03-23}
  s.description = %q{longer description of your gem}
  s.email = %q{github@jake.otherinbox.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/jakewendt-ruby_extension.rb",
    "lib/ruby_extension.rb",
    "lib/ruby_extension/array.rb",
    "lib/ruby_extension/hash.rb",
    "lib/ruby_extension/integer.rb",
    "lib/ruby_extension/nil_class.rb",
    "lib/ruby_extension/object.rb",
    "lib/ruby_extension/string.rb"
  ]
  s.homepage = %q{http://github.com/jakewendt/ruby_extension}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{one-line summary of your gem}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

